steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/libs/*
      build/generated-pom.xml
      build/generated-pom.xml.asc
      build.gradle
      gradlew
      gradlew.bat
      settings.gradle
      gradle.properties
      **/gradle/**
      Scripts/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)/'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'