#Copyright (c) Microsoft Corporation. All rights reserved.
#Licensed under the MIT License.
#Build and test Java Core to make sure a valid pull request is being made
#Validate that the versions dont conflict with those online in case a pull request is made to main or master

pr: 
  branches:
    include:
      - dev
      - main
      - master
  paths:
    exclude:
      - .gradle/wrapper
      - .gitignore
      - CONTRIBUTING.md
      - LICENSE
      - THIRD PARTY NOTICES
      - gradle.properties
      - gradlew
      - gradlew.bat
      - readme.md
      - settings.gradle
      - Scripts/*

trigger: none # disable triggers based on commits.

pool:
  vmImage: windows-latest

steps:
- template: templates/build/checkout-and-credscan.yml
- template: templates/build/install-java.yml
- template: templates/build/build-and-coverage.yml
- template: templates/alert-failure.yml
