# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Publish 

on:
  push:
    branches: [ dev , master ]
    paths:
      - 'src/*'
      - '!.gradle/wrapper'
      - '!.gitignore'
      - '!LICENSE'
      - '!THIRD PARTY NOTICES'
      - '!*.md'
      - '*.gradle'  
env: 
  PREVIEW_TASK: publishSnapshotPublicationToSonatypeSnapshotRepository
  PUBLISH_TASK:  publishMavenCentralReleasePublicationToSonatypeRepository
      
jobs:
  maven_Release:
    if: ${{ github.ref == 'ref/head/master' }}
    environment: 
      name: maven_central_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Easy detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle 
        
    ##Copy the Step below for the other files with the appropriate values    
      - run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH  
        shell: pwsh
        env:  
          ENCODED_VALUE: ""
          OUTPUT_PATH: "" 
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew $PUBLISH_TASK
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: drop
          path: |
            **/libs/*
            build/generated-pom.xml
            build/generated-pom.xml.asc
            build.gradle
            gradlew
            gradlew.bat
            settings.gradle
            gradle.properties
            **/gradle/**
            Scripts/**
  
  githubRelease:
    needs: maven_Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2.0.10
        with: 
          name: drop
          path: drop        
      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: current/working/directory/drop/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  maven_Preview:
    if: ${{ github.ref == 'refs/head/dev' }}
    environment: 
      name: maven_central_snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Easy detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle   
    
    ##Copy the Step below for the other files with the appropriate values    
      - run: .\scripts\decodeAndWrite.ps1 -encodedValue $ENCODED_VALUE -outputPath $OUTPUT_PATH  
        shell: pwsh
        env:  
          ENCODED_VALUE: ""
          OUTPUT_PATH: "" 
    
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew $PREVIEW_TASK
